name: money-trail-dev

x-workspace-volumes: &workspace-volumes
  - ../:/workspaces/money-trail:cached
  - money-trail-uv-cache:/home/vscode/.cache/uv
  - /var/run/docker.sock:/var/run/docker.sock

services:
  workspace:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes: *workspace-volumes
    command: sleep infinity
    environment:
      DBT_PROFILES_DIR: /workspaces/money-trail/dbt
      DATA_DIR: /workspaces/money-trail/data

volumes:
  money-trail-uv-cache:
