parallelism:
  cycles: sequential
  tables: parallel

download_profiles:
  current:
    tables: [indiv, cn, cm, oth, oppexp, ccl, weball, pas2, indexp]
    change_detection: true
  historical:
    tables: [indiv, cn, cm, oth, oppexp, ccl, weball, pas2, indexp]
    change_detection: false

cycles:
  - cycle: 2024
    download_profile: current
  - cycles: "2010-2022"
    download_profile: historical
